"""users, badges, user_badges.

ADR-001: `users` is a PROFILE table keyed to Supabase auth.users.id. There is no
`password_hash` (Supabase owns credentials — ADR-008). `id` is set by the app to
the JWT `sub`; we do NOT hard-FK to auth.users so the identical migration runs on
both local Postgres and Supabase (a Supabase-only FK can be added later).

Deviation (changelog): the spec's per-user `share_percentage` TEXT '40/30/30' is
removed; the split is a single app constant (app.core.constants).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Computed,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, Timestamps, UUIDPrimaryKey
from app.models.enums import Language, MemberRole, MembershipTier, MemberType

_TRUST_NAME_EXPR = (
    "CASE trust_stage "
    "WHEN 0 THEN 'Newcomer' WHEN 1 THEN 'Contributor' "
    "WHEN 2 THEN 'Verified Buyer' WHEN 3 THEN 'Established Reviewer' "
    "WHEN 4 THEN 'Trusted Reviewer' WHEN 5 THEN 'Community Expert' "
    "ELSE 'Unknown' END"
)


class User(Base, Timestamps):
    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint(
            "NOT is_super_admin OR role = 'moderator'",
            name="ck_users_super_admin_is_moderator",
        ),
    )

    # UUID generated app-side (default) and DB-side (server_default) — ADR-010.
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )
    user_id: Mapped[str | None] = mapped_column(String(32), unique=True, index=True)

    #: STAFF-ONLY human reference, "USR-000123". Never authorization, and never
    #: public: it must not appear in any profile, review, feed, HTML, URL,
    #: metadata or analytics payload. It exists so a moderator can read an
    #: account number off a support message and find the person, which a UUID
    #: and the opaque `user_id` above ("usr_a3f9c2b1e4") both make painful.
    #:
    #: Because it is sequential it is enumerable BY DESIGN — that is the point
    #: of a human reference, and precisely why it is staff-only and confers
    #: nothing. Generated by a database DEFAULT drawn from a sequence, so a row
    #: inserted outside the ORM still gets one, and immutable via a trigger.
    #:
    #: `server_default` is declared here on purpose. Without it SQLAlchemy
    #: INSERTs an explicit NULL over the database default and every new account
    #: fails the NOT NULL — the same drift `test_schema_agreement` exists to
    #: catch, and the same one that broke the scheduler's first candidate.
    #: With it declared, the column is omitted from the INSERT and the sequence
    #: supplies the value.
    staff_ref: Mapped[str] = mapped_column(
        String(16), unique=True, index=True, deferred=True,
        server_default=text("'USR-' || lpad(nextval('users_staff_ref_seq')::text, 6, '0')"))

    #: Elevation, deliberately NOT a MemberRole value.
    #:
    #: Roles are user | seller | moderator, and every admin route in this
    #: codebase is gated on `require_role("moderator")`. Adding `super_admin`
    #: to that enum would have made a super admin fail all twenty of those
    #: guards and lock the owner out of the console they own.
    #:
    #: Keeping it orthogonal also makes super-admin UNREPRESENTABLE in the role
    #: transition surface: the staff endpoint writes `role`, and there is no
    #: API path — none — that writes this column. It is granted out of band, by
    #: the owner, directly against the database. That is not a policy statement
    #: this time, it is the shape of the code.
    is_super_admin: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false", nullable=False,
        deferred=True)

    email: Mapped[str] = mapped_column(String(320), unique=True, index=True, nullable=False)
    # Argon2id hash (ADR-011). Nullable so admin/seed accounts can exist w/o a password.
    password_hash: Mapped[str | None] = mapped_column(String(255))
    display_name: Mapped[str | None] = mapped_column(String(120))
    # Stable public handle (Slice 1 Phase A). display_name stays the free-text
    # label; username is the unique, URL-safe identity rendered as @handle.
    #
    # NOT NULL in the DB, so the default matters: any code path that builds a
    # User without going through services.username.allocate_username (seeds,
    # fixtures, admin tooling) would otherwise hit an IntegrityError. The
    # fallback is collision-proof rather than pretty; allocate_username supplies
    # a human-readable handle when one can be derived.
    username: Mapped[str | None] = mapped_column(
        String(32), unique=True, index=True,
        default=lambda: f"user_{uuid.uuid4().hex[:16]}")
    # Public URL of an object in the Supabase Storage `avatars` bucket.
    avatar_url: Mapped[str | None] = mapped_column(Text)
    # Onboarding step 2 ("What do you shop for?") — category slugs that seed the
    # user's feed. Free-form to match products.category, which is also a plain
    # string rather than an enum.
    interests: Mapped[list[str] | None] = mapped_column(JSONB)
    is_suspended: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")

    # Membership tier (M1) — Special/Founding/Standard. Distinct from trust stage.
    membership_tier: Mapped[MembershipTier] = mapped_column(
        Enum(MembershipTier, name="membership_tier"),
        default=MembershipTier.standard, nullable=False,
        server_default=MembershipTier.standard.value,
    )
    role: Mapped[MemberRole] = mapped_column(
        Enum(MemberRole, name="member_role"), default=MemberRole.user, nullable=False,
        server_default=MemberRole.user.value,
    )
    member_type: Mapped[MemberType] = mapped_column(
        Enum(MemberType, name="member_type"), default=MemberType.shopper, nullable=False,
        server_default=MemberType.shopper.value,
    )
    language: Mapped[Language] = mapped_column(
        Enum(Language, name="language"), default=Language.en, nullable=False,
        server_default=Language.en.value,
    )

    # Trust progression (FR-7). reputation_score is 0..100 (ADR-003).
    reputation_score: Mapped[Decimal] = mapped_column(
        Numeric(5, 2), default=0, nullable=False, server_default="0"
    )
    trust_stage: Mapped[int] = mapped_column(
        SmallInteger, default=0, nullable=False, server_default="0"
    )
    trust_level_name: Mapped[str] = mapped_column(
        String(32), Computed(_TRUST_NAME_EXPR, persisted=True)
    )

    # Behavioural aggregates feeding reputation_score / stage unlocks.
    verified_review_count: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    helpfulness_ratio: Mapped[Decimal] = mapped_column(
        Numeric(5, 2), default=0, server_default="0"
    )
    best_answer_count: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    strikes: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    is_on_probation: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false")

    # seller_aggregates and seller_trust_score were the denormalized mirrors of
    # seller_reviews (M2 slice 4). Seller trust ratings were withdrawn from
    # contract on 2026-07-28 and the table is dropped by migration 0024; with
    # their source gone these could only ever hold stale numbers, and a stale
    # trust score is worse than none.
    #
    # Removed from the model BEFORE the migration drops the columns. Doing it
    # the other way round is what took the API down on 2026-08-19: SQLAlchemy
    # emits every mapped column in its SELECT, so a column the model still
    # declares but the database no longer has fails every read of this table.

    # Earnings.
    wallet_balance: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), default=0, nullable=False, server_default="0"
    )
    # Token economy (M2 slice 7): mirrors the append-only token_transactions ledger.
    token_balance: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False, server_default="0"
    )
    # payout_account is sensitive personal data (RA 10173) — PayPal email.
    payout_account: Mapped[str | None] = mapped_column(String(320))

    account_matured_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    badges: Mapped[list[UserBadge]] = relationship(back_populates="user",
                                                   cascade="all, delete-orphan")


class Badge(Base, UUIDPrimaryKey, Timestamps):
    __tablename__ = "badges"

    badge_id: Mapped[str] = mapped_column(String(32), unique=True, index=True)
    name: Mapped[str] = mapped_column(String(80), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    icon: Mapped[str | None] = mapped_column(String(255))
    criteria: Mapped[dict | None] = mapped_column(JSONB)


class UserBadge(Base, UUIDPrimaryKey):
    __tablename__ = "user_badges"
    __table_args__ = (UniqueConstraint("user_id", "badge_id", name="uq_user_badge"),)

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    badge_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("badges.id", ondelete="CASCADE"), nullable=False
    )
    awarded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("now()"), nullable=False
    )

    user: Mapped[User] = relationship(back_populates="badges")
    badge: Mapped[Badge] = relationship()
