"""users.username — unique public handle (Slice 1 Phase A)

Three-phase so it is safe on a populated table: add nullable, backfill a
deterministic slug for every existing row, then constrain.

The SQL slug mirrors app/services/username.py exactly — lowercase, ASCII-ish
fold, non-alphanumerics to '_', collapse runs, trim, cap at 32 — so a handle
generated at runtime and one generated by this backfill follow the same rules.
Source preference: display_name -> email local-part -> the literal 'user'.

ROW_NUMBER over the slug partition supplies collision suffixes; rn = 1 keeps the
bare slug so the common case reads naturally.

Revision ID: 0016_username
Revises: 0015_email_otp
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0016_username"
down_revision = "0015_email_otp"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("users", sa.Column("username", sa.String(length=32), nullable=True))

    op.execute("""
        WITH slugged AS (
            SELECT id,
                   COALESCE(
                     NULLIF(
                       LEFT(
                         TRIM(BOTH '_' FROM
                           REGEXP_REPLACE(
                             REGEXP_REPLACE(
                               LOWER(COALESCE(NULLIF(TRIM(display_name), ''),
                                              split_part(email, '@', 1))),
                               '[^a-z0-9]+', '_', 'g'),
                             '_{2,}', '_', 'g')),
                         32),
                       ''),
                     'user') AS base
            FROM users
        ), numbered AS (
            SELECT id, base,
                   ROW_NUMBER() OVER (PARTITION BY base ORDER BY id) AS rn
            FROM slugged
        )
        UPDATE users u
           SET username = CASE
                            WHEN n.rn = 1 THEN n.base
                            ELSE LEFT(n.base, 32 - LENGTH(n.rn::text))
                                 || n.rn::text
                          END
          FROM numbered n
         WHERE u.id = n.id AND u.username IS NULL
    """)

    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.alter_column("users", "username", nullable=False)


def downgrade() -> None:
    op.drop_index("ix_users_username", table_name="users")
    op.drop_column("users", "username")
