"""staff user reference (USR-000123) and the super-admin elevation flag

TWO ADDITIVE THINGS, neither of which changes an existing column's meaning.

STAFF REFERENCE. `users.staff_ref`, "USR-000123". Staff-only and never
authorization: it appears in no public profile, review, feed, HTML, URL,
metadata or analytics payload, and possession of one grants nothing. It exists
because moderators currently have to match people by UUID or by `user_id`
("usr_a3f9c2b1e4"), neither of which a human can read back off a support
message.

Generated by a column DEFAULT drawn from a SEQUENCE rather than in Python. That
matters for three reasons: a row inserted by a script, a fixture or a raw SQL
statement still gets one; two concurrent inserts cannot collide, because a
sequence never hands out the same value twice even in rolled-back transactions;
and the application cannot forget to set it.

Being sequential makes it enumerable. That is deliberate — a human reference
that is not sequential is not human-friendly — and it is exactly why the column
is staff-only and carries no authority. Enumerating staff refs tells an
attacker how many accounts exist, which is why it is never emitted publicly.

BACKFILL is deterministic: existing rows are numbered by (created_at, id), so
the same database always produces the same assignment, and a re-run is a no-op
because only NULL rows are touched. The sequence is then advanced past the
high-water mark so new accounts cannot collide with backfilled ones.

IMMUTABILITY is a trigger, not a convention. A staff reference that could be
edited would be worse than none at all: support history, audit context and
screenshots would all silently start pointing at a different person.

SUPER-ADMIN FLAG. `users.is_super_admin`, orthogonal to `member_role`.

`super_admin` is deliberately NOT added to the member_role enum. Every admin
route in this codebase is gated on require_role("moderator"); a super admin
whose role was "super_admin" would fail all of them and be locked out of the
console. Worse, adding it to the enum would put super-admin inside the very
surface the role-change endpoint writes to.

As a separate column it is unreachable from the API: the staff endpoint writes
`role` and nothing writes this. It is granted out of band by the owner, so no
in-product privilege escalation path to super-admin exists at all.

The NOT NULL tightening and audit enum values deliberately live in 0039 and
0040. The repository's migration classifier requires backfill-before-tighten,
and PostgreSQL enum additions must be alone in their migration.
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0038_staff_ref_and_super_admin"
down_revision = "0037_cron_lease"
branch_labels = None
depends_on = None

SEQUENCE = "users_staff_ref_seq"
#: 'USR-' + six digits fits in 10; the column is 16 so a seventh and eighth
#: digit need no migration. lpad only pads, it never truncates, so passing
#: 1,000,000 simply yields USR-1000000 rather than a duplicate.
REF_EXPR = f"'USR-' || lpad(nextval('{SEQUENCE}')::text, 6, '0')"


def upgrade() -> None:
    # --- The elevation flag -------------------------------------------------
    op.add_column("users", sa.Column(
        "is_super_admin", sa.Boolean(), nullable=False, server_default="false"))
    op.create_check_constraint(
        "ck_users_super_admin_is_moderator",
        "users",
        "NOT is_super_admin OR role = 'moderator'",
    )

    # --- The staff reference ------------------------------------------------
    op.execute(f"CREATE SEQUENCE IF NOT EXISTS {SEQUENCE}")
    op.add_column("users", sa.Column("staff_ref", sa.String(16), nullable=True))

    # Deterministic backfill: oldest account first, id breaking any tie so the
    # ordering is total. Only NULL rows are touched, so this is re-runnable.
    op.execute("""
        WITH ordered AS (
            SELECT id, row_number() OVER (ORDER BY created_at, id) AS n
            FROM users
            WHERE staff_ref IS NULL
        )
        UPDATE users u
           SET staff_ref = 'USR-' || lpad(ordered.n::text, 6, '0')
          FROM ordered
         WHERE u.id = ordered.id
    """)

    # Advance the sequence past everything the backfill assigned, so the first
    # new account does not collide with an existing row. Reading the maximum
    # back from the table rather than trusting the row count means an
    # interrupted or partially-applied backfill still lands somewhere safe.
    op.execute(f"""
        WITH ref_high_water AS (
            SELECT COALESCE(
                MAX(NULLIF(regexp_replace(staff_ref, '\\D', '', 'g'), ''))::bigint,
                0
            ) AS n
            FROM users WHERE staff_ref LIKE 'USR-%'
        )
        SELECT setval('{SEQUENCE}', GREATEST(n, 1), n > 0)
        FROM ref_high_water
    """)

    op.alter_column("users", "staff_ref", server_default=sa.text(REF_EXPR))
    # Named as SQLAlchemy would name `unique=True, index=True` on the model, so
    # the two descriptions of this index agree and autogenerate stays quiet.
    op.create_index("ix_users_staff_ref", "users", ["staff_ref"], unique=True)

    # Immutability. A reference that can be edited breaks every support thread
    # and audit record that ever quoted it.
    op.execute("""
        CREATE OR REPLACE FUNCTION users_staff_ref_is_immutable()
        RETURNS trigger AS $$
        BEGIN
            IF NEW.staff_ref IS DISTINCT FROM OLD.staff_ref THEN
                RAISE EXCEPTION
                    'users.staff_ref is immutable (% -> %)', OLD.staff_ref, NEW.staff_ref
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER trg_users_staff_ref_immutable
        BEFORE UPDATE OF staff_ref ON users
        FOR EACH ROW EXECUTE FUNCTION users_staff_ref_is_immutable()
    """)

def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_users_staff_ref_immutable ON users")
    op.execute("DROP FUNCTION IF EXISTS users_staff_ref_is_immutable()")
    op.drop_index("ix_users_staff_ref", table_name="users")
    op.drop_column("users", "staff_ref")
    op.execute(f"DROP SEQUENCE IF EXISTS {SEQUENCE}")
    op.drop_constraint(
        "ck_users_super_admin_is_moderator", "users", type_="check")
    op.drop_column("users", "is_super_admin")
