"""initial 15-table schema

Revision ID: 34e54f57eca0
Revises: 
Create Date: 2026-07-12 19:55:00.607196
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '34e54f57eca0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('badge_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_badge_id'), 'badges', ['badge_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('user', 'seller', 'moderator', name='member_role'), server_default='user', nullable=False),
    sa.Column('member_type', sa.Enum('shopper', 'seller', 'moderator', name='member_type'), server_default='shopper', nullable=False),
    sa.Column('language', sa.Enum('en', 'fil', 'tl_x_taglish', name='language'), server_default='en', nullable=False),
    sa.Column('reputation_score', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('trust_stage', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('trust_level_name', sa.String(length=32), sa.Computed("CASE trust_stage WHEN 0 THEN 'Newcomer' WHEN 1 THEN 'Contributor' WHEN 2 THEN 'Verified Buyer' WHEN 3 THEN 'Established Reviewer' WHEN 4 THEN 'Trusted Reviewer' WHEN 5 THEN 'Community Expert' ELSE 'Unknown' END", persisted=True), nullable=False),
    sa.Column('verified_review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('helpfulness_ratio', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('best_answer_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('strikes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_on_probation', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('seller_aggregates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wallet_balance', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('payout_account', sa.String(length=320), nullable=True),
    sa.Column('account_matured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('moderation_logs',
    sa.Column('log_id', sa.String(length=48), nullable=True),
    sa.Column('target_type', sa.Enum('review', 'answer', 'seller_review', 'question', 'user', name='moderation_target_type'), nullable=True),
    sa.Column('target_ref', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('moderator_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('report', 'approve', 'reject', 'remove', 'penalize', 'suspend', 'restore', 'override', 'escalate', 'csv_import', 'payout', 'honesty_fund_distribution', name='moderation_action'), nullable=False),
    sa.Column('reason', sa.Enum('fake_proof', 'plagiarized', 'spam', 'harassment', 'conflict_of_interest', 'seller_posing_as_buyer', 'other', name='moderation_reason'), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_log_id'), 'moderation_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_moderation_logs_target_ref'), 'moderation_logs', ['target_ref'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('line', sa.String(length=120), nullable=True),
    sa.Column('key_spec', sa.String(length=120), nullable=True),
    sa.Column('descriptor', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('pending', 'canonicalized', 'rejected', name='product_status'), server_default='pending', nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), server_default='0', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('aggregated_pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aggregated_cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_canonical_name'), 'products', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=True)
    op.create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_table('price_history',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('shopee', 'lazada', 'other', name='platform'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('variant', sa.String(length=120), nullable=True),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_platforms',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('shopee', 'lazada', 'other', name='platform'), nullable=False),
    sa.Column('platform_url', sa.Text(), nullable=True),
    sa.Column('is_monetizable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'platform', 'platform_url', name='uq_product_platform')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('asker_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('directed_to', sa.Enum('buyers', 'seller', name='question_directed_to'), nullable=False),
    sa.Column('best_answer_id', sa.UUID(), nullable=True),
    sa.Column('is_removed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['best_answer_id'], ['answers.id'], name='fk_questions_best_answer', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=True)
    op.create_table('reviews',
    sa.Column('review_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('discussion', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Enum('yes_absolutely', 'it_depends', 'hard_pass', name='verdict'), nullable=False),
    sa.Column('verdict_explanation', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('anti_target_audience', sa.Text(), nullable=True),
    sa.Column('star_rating', sa.SmallInteger(), nullable=False),
    sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('price_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'unverified', name='verification_status'), server_default='unverified', nullable=False),
    sa.Column('verification_tier', sa.Enum('tier_0', 'tier_1', name='verification_tier'), server_default='tier_0', nullable=False),
    sa.Column('helpful_votes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unhelpful_votes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wilson_score', sa.Numeric(precision=6, scale=5), server_default='0', nullable=False),
    sa.Column('is_removed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('earn_eligible_status', sa.Enum('none', 'pending', 'approved', 'rejected', 'monetized', 'honesty_fund', name='earn_eligible_status'), server_default='none', nullable=False),
    sa.Column('affiliate_link', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=True)
    op.create_table('seller_reviews',
    sa.Column('seller_review_id', sa.String(length=32), nullable=True),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('accuracy', sa.Boolean(), nullable=False),
    sa.Column('order_completeness', sa.Boolean(), nullable=False),
    sa.Column('customer_service', sa.SmallInteger(), nullable=False),
    sa.Column('packaging_quality', sa.SmallInteger(), nullable=False),
    sa.Column('overall_rating', sa.SmallInteger(), nullable=False),
    sa.Column('would_recommend', sa.Boolean(), nullable=False),
    sa.Column('proof_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_reviews_seller_review_id'), 'seller_reviews', ['seller_review_id'], unique=True)
    op.create_table('answers',
    sa.Column('answer_id', sa.String(length=32), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('responder_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_best_answer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_first_responder', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('helpful_votes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unhelpful_votes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wilson_score', sa.Numeric(precision=6, scale=5), server_default='0', nullable=False),
    sa.Column('earn_eligible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_answer_id'), 'answers', ['answer_id'], unique=True)
    op.create_table('earn_eligible_votes',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('voter_id', sa.UUID(), nullable=True),
    sa.Column('vote', sa.Enum('up', 'down', name='vote_direction'), nullable=False),
    sa.Column('vote_weight', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('trust_stage_snapshot', sa.Integer(), nullable=False),
    sa.Column('trust_score_snapshot', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('account_age_days_snapshot', sa.Integer(), nullable=False),
    sa.Column('is_probation_snapshot', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'voter_id', name='uq_gate_vote_once')
    )
    op.create_table('honesty_fund_distributions',
    sa.Column('distribution_id', sa.String(length=48), nullable=True),
    sa.Column('cycle_month', sa.Date(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('honesty_score', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('pool_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_month', 'review_id', name='uq_hfd_cycle_review')
    )
    op.create_index(op.f('ix_honesty_fund_distributions_cycle_month'), 'honesty_fund_distributions', ['cycle_month'], unique=False)
    op.create_index(op.f('ix_honesty_fund_distributions_distribution_id'), 'honesty_fund_distributions', ['distribution_id'], unique=True)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=48), nullable=True),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('destination_url', sa.Text(), nullable=True),
    sa.Column('platform', sa.Enum('shopee', 'lazada', 'other', name='platform'), nullable=True),
    sa.Column('click_ref', sa.String(length=128), nullable=True),
    sa.Column('order_ref', sa.String(length=128), nullable=True),
    sa.Column('conversion_status', sa.Enum('clicked', 'converted', 'cancelled', name='conversion_status'), server_default='clicked', nullable=False),
    sa.Column('order_status', sa.String(length=64), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('ua_purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_delete_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_click_ref'), 'sessions', ['click_ref'], unique=False)
    op.create_index(op.f('ix_sessions_ip_delete_at'), 'sessions', ['ip_delete_at'], unique=False)
    op.create_index(op.f('ix_sessions_ip_hash_at'), 'sessions', ['ip_hash_at'], unique=False)
    op.create_index(op.f('ix_sessions_order_ref'), 'sessions', ['order_ref'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_sessions_ua_purge_at'), 'sessions', ['ua_purge_at'], unique=False)
    op.create_table('commissions',
    sa.Column('commission_id', sa.String(length=48), nullable=True),
    sa.Column('target_type', sa.Enum('review', 'answer', name='commission_target'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('answer_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_share', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reviewer_share', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('honesty_fund_share', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='PHP', nullable=False),
    sa.Column('csv_source', sa.String(length=255), nullable=False),
    sa.Column('row_reference', sa.String(length=255), nullable=False),
    sa.Column('order_status', sa.String(length=64), nullable=True),
    sa.Column('is_disputed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cycle_month', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(target_type = 'review' AND review_id IS NOT NULL AND answer_id IS NULL) OR (target_type = 'answer' AND answer_id IS NOT NULL AND review_id IS NULL)", name='ck_commission_target'),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('csv_source', 'row_reference', name='uq_commission_csv_row')
    )
    op.create_index(op.f('ix_commissions_commission_id'), 'commissions', ['commission_id'], unique=True)
    op.create_index(op.f('ix_commissions_cycle_month'), 'commissions', ['cycle_month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commissions_cycle_month'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_commission_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_sessions_ua_purge_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_order_ref'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_ip_hash_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_ip_delete_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_click_ref'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_honesty_fund_distributions_distribution_id'), table_name='honesty_fund_distributions')
    op.drop_index(op.f('ix_honesty_fund_distributions_cycle_month'), table_name='honesty_fund_distributions')
    op.drop_table('honesty_fund_distributions')
    op.drop_table('earn_eligible_votes')
    op.drop_index(op.f('ix_answers_answer_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_seller_reviews_seller_review_id'), table_name='seller_reviews')
    op.drop_table('seller_reviews')
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('product_platforms')
    op.drop_table('price_history')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_canonical_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_moderation_logs_target_ref'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_log_id'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_badges_badge_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###

    # Autogenerate does not drop named ENUM types on downgrade; drop them so a
    # subsequent upgrade can re-CREATE TYPE cleanly (migration reversibility).
    for enum_name in (
        "member_role", "member_type", "language", "moderation_target_type",
        "moderation_action", "moderation_reason", "product_status", "platform",
        "question_directed_to", "verdict", "verification_status",
        "verification_tier", "earn_eligible_status", "vote_direction",
        "conversion_status", "commission_target",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
