"""m1 auth membership review-versions

Revision ID: f18b59a2227b
Revises: 0002_rls_policies
Create Date: 2026-07-12 20:54:53.923555
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f18b59a2227b'
down_revision: Union[str, None] = '0002_rls_policies'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Shared enum referenced by BOTH membership_tiers.code and users.membership_tier.
# create_type=False so the table/column DDL doesn't emit CREATE TYPE; we create it
# once explicitly below (autogen would otherwise CREATE TYPE twice and error).
membership_tier = postgresql.ENUM(
    'special', 'founding', 'standard', name='membership_tier', create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    membership_tier.create(op.get_bind(), checkfirst=True)
    op.create_table('membership_tiers',
    sa.Column('code', membership_tier, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('revenue_share_bps', sa.Integer(), server_default='3000', nullable=False),
    sa.Column('payout_priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('review_versions',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'version_number', name='uq_review_version')
    )
    op.create_foreign_key('fk_questions_best_answer', 'questions', 'answers', ['best_answer_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('reviews', sa.Column('current_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('membership_tier', membership_tier, server_default='standard', nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    # ### end Alembic commands ###

    # M0 left users.id without a DB default (it was app-assigned to the Supabase
    # uid). ADR-010 makes it an ordinary generated PK — add the server default.
    op.alter_column('users', 'id', server_default=sa.text('gen_random_uuid()'))

    # RLS on the new tables (defense-in-depth; consistent with M0). Public read;
    # writes go through the owner/service connection.
    op.execute("ALTER TABLE membership_tiers ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY membership_tiers_select_public ON membership_tiers "
               "FOR SELECT USING (true)")
    op.execute("ALTER TABLE review_versions ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY review_versions_select_public ON review_versions "
               "FOR SELECT USING (true)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS review_versions_select_public ON review_versions")
    op.execute("DROP POLICY IF EXISTS membership_tiers_select_public ON membership_tiers")
    op.alter_column('users', 'id', server_default=None)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.drop_column('users', 'membership_tier')
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'password_hash')
    op.drop_column('reviews', 'current_version')
    op.drop_constraint('fk_questions_best_answer', 'questions', type_='foreignkey')
    op.drop_table('review_versions')
    op.drop_table('membership_tiers')
    membership_tier.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
